name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Check secret available
      env:
        SECRET_DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        SECRET_DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      run: |
        if [[ -z "$SECRET_DOCKERHUB_PASSWORD" ]]; then
          echo "Missing variable SECRET_DOCKERHUB_PASSWORD"
          exit 1
        fi
    - name: Check variables
      env:
        EVENT_NAME: ${{ github.event_name }}
        REPO_NAME: ${{ github.event.repository.name }}
        REPO_HEAD_REF: ${{ github.head_ref }}
        REPO_REF: ${{ github.ref}}
      run: echo "event name $EVENT_NAME head_branch $REPO_HEAD_REF $REPO_REF"
    - name: Check image name
      env:
        REPO_NAME: ${{ github.event.repository.name }}
      run: echo "docker image name would be $REPO_NAME:latest"
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Build the Docker image
      env:
        REPO_NAME: ${{ github.event.repository.name }}
      run: docker build . --file Dockerfile --tag eurobenchtest/$REPO_NAME:latest
    - name: test the Docker image
      env:
        DOCKER_IMAGE: eurobenchtest/${{ github.event.repository.name }}:latest
      run:  python3 tests/test_docker_call.py
    - name: Push to Docker hub
      env:
        REPO_NAME: ${{ github.event.repository.name }}
      run: docker push eurobenchtest/$REPO_NAME:latest
